.TH CYGNUS-SHOT 1.1 "March 2026" "Version 1.1" "Cygnus Screen Capture"
.SH NAME
cygnus-shot \- screenshot utility for Cygnus WM

.SH SYNOPSIS
.B cygnus-shot
[\fB\-a\fR] [\fIFILENAME\fR]

.SH DESCRIPTION
.B cygnus-shot
is a simple screen capture tool for the Cygnus Window Manager. By default, it captures the entire screen and saves it as a JPEG file.

.SH OPTIONS
.TP
.B \-a
Interactively select an area or a window to capture.
.TP
.I FILENAME
The name of the file to save the screenshot to. If not provided, it saves to \fBscreenshot.jpg\fR in the current directory.

.SH AUTHOR
Jonathan Torres

.SH LICENSE
Licensed under GPL v3.0-or-later
