.TH CYGNUS-CALC 1.3 "March 2026" "Version 1.3" "Cygnus Calculator"
.SH NAME
cygnus-calc \- minimalist calculator for Cygnus WM

.SH SYNOPSIS
.B cygnus-calc

.SH DESCRIPTION
.B cygnus-calc
is a minimalist calculator utility written for the Cygnus Window Manager. It features standard arithmetic and common scientific functions like square root.

.SH AUTHOR
Jonathan Torres

.SH LICENSE
Licensed under GPL v3.0-or-later
