.TH CYGNUS-CAM 0.8 "March 2026" "Version 0.8" "Cygnus Webcam App"
.SH NAME
cygnus-cam \- lightweight webcam app for Cygnus WM

.SH SYNOPSIS
.B cygnus-cam

.SH DESCRIPTION
.B cygnus-cam
is a simple, fast webcam app written for the Cygnus Window Manager. It shows a live-stream feed of the webcam and allows the user to take a snapshot, which will be saved in the user's home/Pictures directory.

.SH AUTHOR
Jonathan Torres

.SH LICENSES
Licensed under GPL v3.0-or-later
stb_image_write.h library used under MIT license
